language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_script:
  - composer self-update
  - composer update --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
